Deployment toolchain
pwn-ble/pwnable pull request #4
Opened 2021-03-18 22:06 UTC by averywald

we can start from here, and add custom linux configurations through docker for further features

2021-03-18 22:39 UTC, averywald commented
actually we might want to rename `/src` to `/deployment`

2021-03-22 22:35 UTC, yukun2h4ng approved these changes

2021-03-22 22:44 UTC, yukun2h4ng requested changes

2021-03-22 22:44 UTC, yukun2h4ng commented on src/hello.c
> +
add #include <stdio.h>

2021-03-22 22:50 UTC, averywald commented on src/hello.c
> +
tru

2021-03-22 23:10 UTC, yukun2h4ng approved these changes

2021-03-23 15:57 UTC, merged